/*!
 * jQuery BBQ: Back Button & Query Library - v1.3pre - 8/26/2010
 * http://benalman.com/projects/jquery-bbq-plugin/
 *
 * Copyright (c) 2010 "Cowboy" Ben Alman
 * Dual licensed under the MIT and GPL licenses.
 * http://benalman.com/about/license/
 */
(function(e){function t(a){return typeof a==="string"}function q(a){var b=B.call(arguments,1);return function(){return a.apply(this,b.concat(B.call(arguments)))}}function C(a,b,c,d,g){var i;if(d!==j){b=c.match(a?u:/^([^#?]*)\??([^#]*)(#?.*)/);c=b[3]||"";if(g===2&&t(d))d=d.replace(a?v:D,"");else{i=l(b[2]);d=t(d)?l[a?n:r](d):d;d=g===2?d:g===1?e.extend({},d,i):e.extend({},i,d);d=E(d);if(a)d=d.replace(F,x)}a=b[1]+(a?y:d||!b[1]?"?":"")+d+c}else a=b(c!==j?c:location.href);return a}function G(a,b,c){if(b===
j||typeof b==="boolean"){c=b;b=s[a?n:r]()}else b=t(b)?b.replace(a?v:D,""):b;return l(b,c)}function H(a,b,c,d){if(!t(c)&&typeof c!=="object"){d=c;c=b;b=j}return this.each(function(){var g=e(this),i=b||I()[(this.nodeName||"").toLowerCase()]||"",f=i&&g.attr(i)||"";g.attr(i,s[a](f,c,d))})}var j,B=Array.prototype.slice,x=decodeURIComponent,s=e.param,E,o,l,z,A=e.bbq=e.bbq||{},J,K,I,L=e.event.special,r="querystring",n="fragment",D=/^.*\?|#.*$/g,v,u,F,M,y,N={};s[r]=q(C,0,function(a){return a.replace(/(?:^[^?#]*\?([^#]*).*$)?.*/,
"$1")});s[n]=o=q(C,1,function(a){return a.replace(u,"$2")});s.sorted=E=function(a,b){var c=[],d={};e.each(s(a,b).split("&"),function(g,i){var f=i.replace(/(?:%5B|=).*$/,""),h=d[f];if(!h){h=d[f]=[];c.push(f)}h.push(i)});return e.map(c.sort(),function(g){return d[g]}).join("&")};o.noEscape=function(a){a=a||"";a=e.map(a.split(""),encodeURIComponent);F=RegExp(a.join("|"),"g")};o.noEscape(",/");o.ajaxCrawlable=function(a){if(a!==j){if(a){v=/^.*(?:#!|#)/;u=/^([^#]*)(?:#!|#)?(.*)$/;y="#!"}else{v=/^.*#/;
u=/^([^#]*)#?(.*)$/;y="#"}M=!!a}return M};o.ajaxCrawlable(0);e.deparam=l=function(a,b){var c={},d={"true":true,"false":false,"null":null};e.each(a.replace(/\+/g," ").split("&"),function(g,i){var f=i.split("="),h=x(f[0]),w=c,p=0,k=h.split("]["),m=k.length-1;if(/\[/.test(k[0])&&/\]$/.test(k[m])){k[m]=k[m].replace(/\]$/,"");k=k.shift().split("[").concat(k);m=k.length-1}else m=0;if(f.length===2){f=x(f[1]);if(b)f=f&&!isNaN(f)?+f:f==="undefined"?j:d[f]!==j?d[f]:f;if(m)for(;p<=m;p++){h=k[p]===""?w.length:
k[p];w=w[h]=p<m?w[h]||(k[p+1]&&isNaN(k[p+1])?{}:[]):f}else if(e.isArray(c[h]))c[h].push(f);else c[h]=c[h]!==j?[c[h],f]:f}else if(h)c[h]=b?j:""});return c};l[r]=q(G,0);l[n]=z=q(G,1);e.elemUrlAttr||(e.elemUrlAttr=function(a){return e.extend(N,a)})({a:"href",base:"href",iframe:"src",img:"src",input:"src",form:"action",link:"href",script:"src"});I=e.elemUrlAttr;e.fn[r]=q(H,r);e.fn[n]=q(H,n);A.pushState=J=function(a,b){if(t(a)&&/^#/.test(a)&&b===j)b=2;var c=a!==j;c=o(location.href,c?a:{},c?b:2);location.href=
c};A.getState=K=function(a,b){return a===j||typeof a==="boolean"?z(a):z(b)[a]};A.removeState=function(a){var b={};if(a!==j){b=K();e.each(e.isArray(a)?a:arguments,function(c,d){delete b[d]})}J(b,2)};L.hashchange=e.extend(L.hashchange,{add:function(a){var b;b=a.handler;a.handler=function(c){var d=c[n]=o();c.getState=function(g,i){return g===j||typeof g==="boolean"?l(d,g):l(d,i)[g]};b.apply(this,arguments)}}})})(jQuery,this);
